# https://docs.gitlab.com/ce/ci/yaml/README.html

image: python:2.7

before_script:
  - apt-get update  # for docker

install:
  # only:
  #   - triggers
  script:
    - make debian-nosudo
    - source venv_create.sh
    - workon abelujo
    - pip install -U pip
    - make install-nosudo