# https://docs.gitlab.com/ce/ci/yaml/README.html

image: python:2.7

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get update  # for docker

install:
  # every commit don't need to fire this test.
  # only:
  #   - triggers
  script:
    - make debian-nosudo
    # mkvirtualenv fails with no output :/
    - virtualenv .
    - source bin/activate
    - echo "working on abelujo venv"
    - echo "upgranding pip"
    - pip install -U pip
    - echo "running install-nosudo"
    - make install-nosudo