# https://docs.gitlab.com/ce/ci/yaml/README.html

image: python:2.7

before_script:
  - apt-get update  # for docker
  - echo "pull and rebase repo"
  - git pull --rebase gitlab master
  - echo "update submodules"
  - git submodule update --remote

install:
  # only:
  #   - triggers
  script:
    - make debian-nosudo
    - virtualenv .
    - source bin/activate
    - echo "working on abelujo venv"
    - echo "upgranding pip"
    - pip install -U pip
    - echo "running install-nosudo"
    - make install-nosudo