# https://docs.gitlab.com/ce/ci/yaml/README.html

# We try a ready image with nodejs and python, instead of the python:2.7
# Easier, but we don't test nodejs installation.
image: beevelop/nodejs-python

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - release

cache:
  paths:
  - node_modules/
  - .yarn

before_script:
  - apt-get update -qy  # for docker

test:
  stage: test
  script:
    - make debian-nosudo
    - virtualenv .
    - source bin/activate
    - pip install -U pip
    - make pip-nosudo
    - make pip-dev
    - make db
    - redis-server &  # for redis cache
    - make

install:
  stage: release
  # Build everything only when a new tag is pushed. A waste to do everytime.
  only:
    - tags
  script:
    - make debian-nosudo
    - make install-yarn
    - node --version
    - yarn --version
    # mkvirtualenv fails with no output :/
    - virtualenv .
    - source bin/activate
    - echo "working on abelujo venv"
    - echo "upgranding pip"
    - pip install -U pip
    - echo "running install-nosudo"
    - make install-nosudo
    - python manage.py check
